server:
  port: 8099

spring:
  profiles:
    active: native
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
       #git:
        #本地Git仓库
         #uri: file://C:\Users\Byron\Desktop\properties
         #{application}/{profile}名称 如果没有则使用上面的uri属性
         #clone-on-start: true
       native: file://C:\Users\Byron\Desktop\properties
#注册到配置eurake
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    ip-address: 127.0.0.1
    #将自己ip 注册到eureka
    prefer-ip-address: true
