server:
  port: 8088

spring:
  application:
    name: microservice-gateway-zuul


#注册到服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

#actuator 开放所有页面
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #health显示详情
  endpoint:
    health:
      show-details: always