server:
  port: 8082

spring:
  application:
    name: microservice-consumer-movie
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
  #rabbitmq:
    #host: localhost
    #port: 5672
    #username: guest
    #password: guest
logging:
  level:
    root: info
    com.zhujun.feign.UserFeignClient: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  #health显示详情
  endpoint:
    health:
      show-details: always

feign:
  hystrix:
    enabled: true


